<?php

namespace Appload\ProjectsHub\Console\Commands;

use Illuminate\Console\Command;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

class OpenApiDiffCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'projects-hub:openapi:diff
        {--ref=origin/main : Git ref used as baseline, for example origin/main or v1.0.1}
        {--mode=breaking : oasdiff mode: breaking or changelog}
        {--output= : Optional file path for the generated report}
        {--fetch : Fetch the remote ref before reading the baseline}
        {--no-generate : Skip l5-swagger generation and use the current spec as revision}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Compare the current OpenAPI spec with a baseline from Git using oasdiff.';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $ref = (string) $this->option('ref');
        $mode = (string) $this->option('mode');
        $output = $this->option('output');
        $shouldFetch = (bool) $this->option('fetch');
        $shouldGenerate = ! (bool) $this->option('no-generate');

        if (!in_array($mode, ['breaking', 'changelog'], true)) {
            $this->error("Unsupported mode [{$mode}]. Allowed values: breaking, changelog.");

            return self::FAILURE;
        }

        if (!$this->binaryExists('git')) {
            $this->error('git is not available in PATH.');

            return self::FAILURE;
        }

        if (!$this->binaryExists('oasdiff')) {
            $this->error('oasdiff is not installed or not available in PATH.');
            $this->line('Install it on macOS with: brew install oasdiff');

            return self::FAILURE;
        }

        if ($shouldFetch) {
            $fetchTarget = $this->resolveFetchTarget($ref);

            if ($fetchTarget === null) {
                $this->warn("Skipping fetch: ref [{$ref}] is not in remote/branch format.");
            } else {
                [$remote, $branch] = $fetchTarget;
                $this->line("Fetching latest baseline from {$remote}/{$branch}...");
                $this->runProcess(['git', 'fetch', $remote, $branch]);
            }
        }

        $baselinePath = $this->makeTempFile('openapi-base-');
        $revisionPath = $this->makeTempFile('openapi-revision-');

        try {
            $this->line("Extracting baseline spec from [{$ref}]...");
            // dd(['git', 'show', "{$ref}:". config('projects-hub.openapi_docs_path')]);
            $baseline = $this->runProcess(['git', 'show', "{$ref}:". config('projects-hub.openapi_docs_path')]);

            file_put_contents($baselinePath, $baseline);

            if ($shouldGenerate) {
                $this->line('Generating current OpenAPI spec with l5-swagger...');
                $status = $this->call('l5-swagger:generate');

                if ($status !== self::SUCCESS) {
                    $this->error('l5-swagger generation failed.');

                    return self::FAILURE;
                }
            }

            $currentSpecPath = base_path(config('projects-hub.openapi_docs_path'));

            if (!is_file($currentSpecPath)) {
                $this->error("Current OpenAPI spec not found at [{$currentSpecPath}].");

                return self::FAILURE;
            }

            copy($currentSpecPath, $revisionPath);

            $command = ['oasdiff', $mode, $baselinePath, $revisionPath];

            if ($mode === 'changelog' && $output) {
                $command[] = '--format';
                $command[] = 'markdown';
            }

            $this->line("Running oasdiff in [{$mode}] mode...");
            $report = $this->runProcess($command);

            if ($output) {
                $outputPath = $this->resolveOutputPath((string) $output);
                $outputDir = dirname($outputPath);

                if (!is_dir($outputDir)) {
                    mkdir($outputDir, 0755, true);
                }

                file_put_contents($outputPath, $report);
                $this->info("Report written to [{$outputPath}]");
            }

            $this->newLine();
            $this->line($report === '' ? 'No output generated by oasdiff.' : $report);

            return self::SUCCESS;
        } catch (ProcessFailedException $exception) {
            $this->error($exception->getMessage());

            return self::FAILURE;
        } finally {
            @unlink($baselinePath);
            @unlink($revisionPath);
        }
    }

    private function binaryExists(string $binary): bool
    {
        $process = new Process(['which', $binary], base_path());
        $process->run();

        return $process->isSuccessful();
    }

    /**
     * @return array{string, string}|null
     */
    private function resolveFetchTarget(string $ref): ?array
    {
        $segments = explode('/', $ref, 2);

        if (count($segments) !== 2 || $segments[0] === '' || $segments[1] === '') {
            return null;
        }

        return [$segments[0], $segments[1]];
    }

    private function makeTempFile(string $prefix): string
    {
        $path = tempnam(sys_get_temp_dir(), $prefix);

        if ($path === false) {
            throw new \RuntimeException('Unable to create a temporary file.');
        }

        return $path;
    }

    private function resolveOutputPath(string $output): string
    {
        if (str_starts_with($output, DIRECTORY_SEPARATOR)) {
            return $output;
        }

        return base_path($output);
    }

    private function runProcess(array $command): string
    {
        $process = new Process($command, base_path());
        $process->setTimeout(300);
        $process->run();

        if (!$process->isSuccessful()) {
            throw new ProcessFailedException($process);
        }

        return trim($process->getOutput());
    }
}
