<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Projects Hub Integration
    |--------------------------------------------------------------------------
    |
    | Enables or disables the package routes.
    |
    | When disabled, the package will not expose its API endpoints.
    |
    */
    'enabled' => env('PROJECTS_HUB_ENABLED', true),

    /*
    |--------------------------------------------------------------------------
    | OpenAPI Documentation Path
    |--------------------------------------------------------------------------
    |
    | Relative path to the OpenAPI JSON file generated by the application.
    |
    | By default, the package expects the file inside the host Laravel project:
    |
    | storage/api-docs/api-docs.json
    |
    | You can override this value from .env if your OpenAPI file is generated
    | in a different location.
    |
    */
    'openapi_docs_path' => env(
        'PROJECTS_HUB_OPENAPI_DOCS_PATH',
        'storage/api-docs/api-docs.json'
    ),

    /*
    |--------------------------------------------------------------------------
    | Package Routes
    |--------------------------------------------------------------------------
    |
    | Configuration for the routes exposed by this package.
    |
    | The default prefix exposes the endpoints under:
    |
    | /api/projects-hub
    |
    | For example:
    |
    | /api/projects-hub/v1/openapi
    |
    */
    'route' => [
        /*
        |--------------------------------------------------------------------------
        | Route Prefix
        |--------------------------------------------------------------------------
        |
        | Prefix used for all Projects Hub package endpoints.
        |
        */
        'prefix' => env('PROJECTS_HUB_ROUTE_PREFIX', 'api/projects-hub'),

        /*
        |--------------------------------------------------------------------------
        | Route Middleware
        |--------------------------------------------------------------------------
        |
        | Middleware applied to all package routes.
        |
        | The default "api" middleware group is usually enough for internal
        | JSON endpoints.
        |
        | Authentication for Projects Hub is configured separately below.
        |
        */
        'middleware' => ['api'],

        /*
        |--------------------------------------------------------------------------
        | Route Authentication
        |--------------------------------------------------------------------------
        |
        | Optional X-API-Key authentication for the package endpoints.
        |
        | When enabled, every request must include this header:
        |
        | X-API-Key: your-api-key
        |
        | If authentication is enabled but no API key is configured, requests
        | should fail because the application is not configured correctly.
        |
        */
        'auth' => [
            /*
            |--------------------------------------------------------------------------
            | Enable Route Authentication
            |--------------------------------------------------------------------------
            |
            | Set to true to protect Projects Hub endpoints with X-API-Key.
            |
            */
            'enabled' => env('PROJECTS_HUB_AUTH_ENABLED', false),

            /*
            |--------------------------------------------------------------------------
            | Expected X-API-Key Value
            |--------------------------------------------------------------------------
            |
            | The API key that Projects Hub must send in the X-API-Key header.
            |
            | Keep this value in .env and do not hardcode secrets here.
            |
            */
            'x-api-key' => env('PROJECTS_HUB_AUTH_X_API_KEY'),
        ],
    ],
];